import './globals.css'
import type { Metadata } from 'next'
import { Raleway } from 'next/font/google'
import { cn } from "@/lib/utils";
import Navbar from '@/components/Navbar';

const raleway = Raleway({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'UaiSearch',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(raleway.className)}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
